

# This file was *autogenerated* from the file V333535_3-1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_5 = Integer(5)
def R(p0, p1, p2, p3, p4, p5):
    return matrix([p3, p4, p5]).transpose()*matrix([p0, p1, p2]).inverse().transpose()

var('phi')
k = NumberField(phi**_sage_const_2  - phi - _sage_const_1 , names=('phi',)); (phi,) = k._first_ngens(1)

p0 = vector([_sage_const_1 , _sage_const_0 , phi])
p1 = vector([phi, -_sage_const_1 , _sage_const_0 ])
p2 = vector([phi, _sage_const_1 , _sage_const_0 ])

p3 = vector([_sage_const_0 , phi, -_sage_const_1 ])
p4 = vector([_sage_const_0 , phi, _sage_const_1 ])
p5 = vector([_sage_const_1 , _sage_const_0 , phi])
p6 = vector([phi, -_sage_const_1 , _sage_const_0 ])
p7 = vector([_sage_const_1 , _sage_const_0 , -phi])

R3 = R(p0, p1, p2, p1, p2, p0)
R53 = R(p3, p4, p5, p6, p7, p3)

l = k['xi']; (xi,) = l._first_ngens(1)
k = k.extension(xi**_sage_const_3  - xi - _sage_const_1 , names=('xi',)); (xi,) = k._first_ngens(1)

x = xi
y = ((-_sage_const_4 *phi + _sage_const_8 )*xi + (-_sage_const_4 *phi + _sage_const_4 ))/((_sage_const_4 *phi - _sage_const_8 )*xi + (_sage_const_4 *phi - _sage_const_8 ))
z = _sage_const_2  - phi*x - phi**-_sage_const_1 *y

print(x)
print(y)
print(z)

print()

v = vector([x, y, z])
for i in range(_sage_const_5 ):
    w = R53**i*v
    for j in range(_sage_const_3 ):
        print(i, j, w[j])
        print(w[j].minpoly())
        print()

w = R3*v

r2 = v.dot_product(v)
l2 = (v - w).dot_product(v - w)
mr2 = (v + w).dot_product(v + w)/_sage_const_4 

print(r2)
print(l2)
print(mr2)

print(r2/l2)
print(mr2/l2)

n0 = v + R3*v + R53.inverse()*v
n1 = R3.inverse()*n0
n2 = R53*n0

print(n0)
print(n1)
print(n2)

print(v)

